require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/homeowners", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Homeowner. As you add validations to Homeowner, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Homeowner.create! valid_attributes
      get homeowners_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      homeowner = Homeowner.create! valid_attributes
      get homeowner_url(homeowner)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_homeowner_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      homeowner = Homeowner.create! valid_attributes
      get edit_homeowner_url(homeowner)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Homeowner" do
        expect {
          post homeowners_url, params: { homeowner: valid_attributes }
        }.to change(Homeowner, :count).by(1)
      end

      it "redirects to the created homeowner" do
        post homeowners_url, params: { homeowner: valid_attributes }
        expect(response).to redirect_to(homeowner_url(Homeowner.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Homeowner" do
        expect {
          post homeowners_url, params: { homeowner: invalid_attributes }
        }.to change(Homeowner, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post homeowners_url, params: { homeowner: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested homeowner" do
        homeowner = Homeowner.create! valid_attributes
        patch homeowner_url(homeowner), params: { homeowner: new_attributes }
        homeowner.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the homeowner" do
        homeowner = Homeowner.create! valid_attributes
        patch homeowner_url(homeowner), params: { homeowner: new_attributes }
        homeowner.reload
        expect(response).to redirect_to(homeowner_url(homeowner))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        homeowner = Homeowner.create! valid_attributes
        patch homeowner_url(homeowner), params: { homeowner: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested homeowner" do
      homeowner = Homeowner.create! valid_attributes
      expect {
        delete homeowner_url(homeowner)
      }.to change(Homeowner, :count).by(-1)
    end

    it "redirects to the homeowners list" do
      homeowner = Homeowner.create! valid_attributes
      delete homeowner_url(homeowner)
      expect(response).to redirect_to(homeowners_url)
    end
  end
end
